### ISSUE TITLE
Dependency conflict

### ISSUE THREAD

**Issue by nellshamrell** [bensadiku/heroku_rs#1]
Looks like one of your dependencies requires an older version of ring  and it conflicts when my project has dependencies that depend on newer versions of ring.

```bash
nell@nsharrington-45404:~/crates-io-ops-bot$ cargo build
    Updating crates.io index
error: failed to select a version for `ring`.
    ... required by package `rustls v0.16.0`
    ... which is depended on by `hyper-rustls v0.19.1`
    ... which is depended on by `reqwest v0.10.2`
    ... which is depended on by `serenity v0.8.0`
    ... which is depended on by `crates-io-ops-bot v0.1.0 (/home/nell/crates-io-ops-bot)`
versions that meet the requirements `^0.16.5` are: 0.16.11, 0.16.10, 0.16.9, 0.16.7, 0.16.6, 0.16.5

the package `ring` links to the native library `ring-asm`, but it conflicts with a previous package which links to `ring-asm` as well:
package `ring v0.14.0`
    ... which is depended on by `rustls v0.15.0`
    ... which is depended on by `hyper-rustls v0.16.1`
    ... which is depended on by `heroku_rs v0.2.0`
    ... which is depended on by `crates-io-ops-bot v0.1.0 (/home/nell/crates-io-ops-bot)`

failed to select a version for `ring` which could resolve this **conflict**
```

**Comment by nellshamrell** [comment]
Doing some more investigation into this

**Comment by nellshamrell** [comment]
Yep - it looks like I can't use both Serenity 0.8.0 and this library in the same Rust project because they depend on different versions of ring

**Comment by nellshamrell** [comment]
Explanation of same issue here https://www.reddit.com/r/rust/comments/dje66k/fixing_crate_version_conflicts/

**Comment by nellshamrell** [comment]
I was able to get around this by using the native_tls_backend rather than rustls_backend with Serenity. This is what is in my Cargo.toml (in case anyone else is trying to use this crate with [Serenity](https://crates.io/crates/serenity)).

```
[dependencies.serenity]
default-features = false
features = ["builder", "cache", "client", "framework", "gateway", "http", "model", "standard_framework", "utils", "native_tls_backend"]
version = "0.8
```

Ideally I would like this crate to be compatible with the latest versions of ring and rustls_backend...but this is a good work around for now.

**Comment by bensadiku** [comment]
Thanks for the in depth investigation, will be updating dependencies for other crates as well, pr's are welcome.

**Comment by bensadiku** [comment]
Did some digging into this, looks like i will have to do a major refactor for the crate, i'd like to add some tests cases before doing this making sure everything works okay afterwards. In the meantime a simpler workaround on this:
 ```toml
[dependencies.heroku_rs]
version = "0.2"
default-features = false
features = ["rust-native-tls"]
```
