### ISSUE TITLE
Rewrite to use more modern crates

### ISSUE THREAD

**Issue by bensadiku** [bensadiku/heroku_rs#5]
Remove hyper, tokio-core, and the old logic where the client owns the event loop. Use something more simple like reqwest for the api calls.

**Comment by nellshamrell** [comment]
I am happy to help with this! I think it might be wise to wait until after the tests are merged in (which I'm happy to help with as well!)

**Comment by bensadiku** [comment]
Thanks a lot Nell, just merged the tests PR. Looking forward to rewriting this.

**Comment by bensadiku** [comment]
Thanks for all the help, Nell.

**Comment by nellshamrell** [comment]
You are very welcome!
